// Page components index file for easier imports
export { default as Login } from './Login';
export { default as SignUp } from './SignUp';
export { default as Home } from './Home';
export { default as PrivateChat } from './PrivateChat';
export { default as RecentChats } from './RecentChats';
export { default as FriendsList } from './FriendsList';
export { default as UpdateProfile } from './UpdateProfile';
export { default as ViewProfile } from './ViewProfile';
export { default as BrowseUsers } from './BrowseUsers';
